export const ActionTypes = {
  SET_MEMBERS: 'SET_MEMBERS',
  SELECTED_MEMBER: 'SELECTED_MEMBER',
  REMOVE_SELECTED_MEMBER: 'REMOVE_SELECTED_MEMBER',
  SET_ORGANIZATIONS: 'SET_ORGANIZATIONS',
  SELECTED_ORGANIZATION: 'SELECTED_ORGANIZATION',
  REMOVE_SELECTED_ORGANIZATION: 'REMOVE_SELECTED_ORGANIZATION',
  NEW_ORGANIZATION: 'NEW_ORGANIZATION',
}
