import React, { useState } from 'react'
import './EnableTwoFactorAuthComponent.Component.css'
import SmsIcon from '../../assets/icons/typing.png'
import DeviceIcon from '../../assets/icons/mobile.png'
import MailIcon from '../../assets/icons/mail.png'
import Button from '@mui/material/Button'
import Brightness1OutlinedIcon from '@mui/icons-material/Brightness1Outlined';
import history from '../../history'


const EnableTwoFactorAuth = () => {
    const [activeTab, setActiveTab] = useState(null)
    return (
        <div className="io__two_fa">
            <div className="io__two_justify">
                <div>
                    <label className="header__label">
                        Enable Two Factor Authentication
                    </label>
                </div>
                <div className="io__two_justify">
                    <label className="info__label">
                        Add an extra layer of security to your Coordination Centric
                        account by enabling two-factor authentication - an entirely
                        optional feature of your account. If enabled you will be
                        required to enter a variable code generated by authenticator
                        app each time you log in.
                    </label>
                </div>
                <div className="io__tf_query">
                    <h4 className="io__query">
                        How would you like to recieve your authentication code
                    </h4>
                </div>
                <div className="io__tf__options">
                    <div className={activeTab === 1 ? 'io__active__option' : 'io__nonActive__option'}>
                        <div
                            className="io__option_icon"
                            onClick={() => {
                                setActiveTab(1)
                            }}
                        >
                            <img src={SmsIcon} alt="sms" />
                        </div>
                        <label className="io__text">SMS</label>
                        <span className={activeTab === 1 ? 'io__active__icon' : 'io__nonactive__icon'}>
                            <Brightness1OutlinedIcon sx={{ color: (activeTab === 1) ? "#E42346" : "#DCDCDC" }} />
                        </span>
                    </div>
                    <div className={activeTab === 2 ? 'io__active__option' : 'io__nonActive__option'}>
                        <div
                            className="io__option_icon"
                            onClick={() => {
                                setActiveTab(2)
                            }}
                        >
                            <img src={MailIcon} alt="email" />
                        </div>
                        <label className="io__text">Email</label>
                        <span className={activeTab === 2 ? 'io__active__icon' : 'io__nonactive__icon'}>
                            <Brightness1OutlinedIcon sx={{ color: (activeTab === 2) ? "#E42346" : "#DCDCDC" }} />
                        </span>
                    </div>
                    <div className={activeTab === 3 ? 'io__active__option' : 'io__nonActive__option'}>
                        <div
                            className="io__option_icon"
                            onClick={() => {
                                setActiveTab(3)
                            }}
                        >
                            <img src={DeviceIcon} alt="app" />
                        </div>
                        <label className="io__text">App</label>
                        <span className={activeTab === 3 ? 'io__active__icon' : 'io__nonactive__icon'}>
                            <Brightness1OutlinedIcon sx={{ color: (activeTab === 3) ? "#E42346" : "#DCDCDC" }} />
                        </span>
                    </div>
                </div>
                <div className="io__continue">
                    <Button
                        type="submit"
                        className="io__Approve__btn"
                        onClick={() => {
                            history.push('/verification')
                        }}
                    >
                        Continue
                    </Button>
                </div>
            </div>
        </div>
    )
}

export default EnableTwoFactorAuth
